site_name: CVMFS → SHPC → Shelley Demo
repo_url: https://github.com/Sydney-Informatics-Hub/cvmfs_shpc_demo
repo_name: Sydney-Informatics-Hub/cvmfs_shpc_demo

nav:
  # Landing page
  - Home: index.md
  - CVMFS: cvmfs.md
  - SHPC: shpc.md
  - Shelley: shelley.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
